### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by ArnolddeBolster** [dezihh/my-harmony-card#1]
Hi,
Looks nice but i tried several things to install.
HACS could not finde this integration
and
Manual install results in this when trying to add a card:
![image](https://github.com/dezihh/my-harmony-card/assets/71195708/4230d02e-b1d3-49f1-9c77-3e942bcb865f)

**Comment by dezihh** [comment]
Hi,
fist let's synchronzie. You have two options:

**HACS install:**

- Goto HACS --> Frontend --> push to the 3 dots at the upper right -->  User defined repositories
- Paste https://github.com/dezihh/my-harmony-card as Repository
- Cathegory --> Lovelance
- Press Add
- After that you should be able to find it under My-Harmony-Card

**Manual Install:**

- Go in the root directory of your installation (this is the directory where you find configuration.yaml too)
- cd www/community/
- mkdir my-harmony-card
- cd my-harmony-card
- wget https://github.com/dezihh/my-harmony-card/releases/download/1.0.2/my-harmony-card.js
- A ls -l my-harmony-card.js should show you my-harmony-card.js
- Next, go to a dashboard of the frontend and switch to edit mode (pencil upper right)
- Push to the 3 dots at the upper right
- Something lile ressource maintencance / add ressource
- Blue button --> Add ressource
- Enter /hacsfiles/my-harmony-card/my-harmony-card.js?hacstag=1718527325 as URL
- Radio button --> Java Script module
- --> Save
- Reload (Shit-F5) your Browserwindow
Done

I recommand option 1 because of updates.
Some buttons may have a different wording, because my system is running german and I tried to translate best as i can here ;-)

Anyway no success?

**Comment by ArnolddeBolster** [comment]
Many thanks for your solution. The HACS install worked as described.
The describtion would be helpfull for other users as well in READ.ME I think
and in addition: After that you should be able to find it under My-Harmony-Card and can download and after restart home assistant  
I'm now gonna configure the remote
Many thanks for you help   !!!!

**Comment by ArnolddeBolster** [comment]
installation worked after extra info
